-- BASIC CONFIGURATION
SET client_encoding = 'UTF8';

BEGIN;

-- TABLES
CREATE TABLE area_units (
    area_unit_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    abbreviation VARCHAR(10) NOT NULL UNIQUE
);

CREATE TABLE farm_status (
    status_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(45) NOT NULL
);

CREATE TABLE farm (
    farm_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    area numeric(10,2) NOT NULL,
    area_unit_id integer NOT NULL,
    status_id integer NOT NULL
);

-- FOREIGN KEYS

ALTER TABLE farm
    ADD CONSTRAINT fk_farm_area_unit_id FOREIGN KEY (area_unit_id) REFERENCES area_units(area_unit_id);

ALTER TABLE farm
    ADD CONSTRAINT fk_farm_status_id FOREIGN KEY (status_id) REFERENCES farm_status(status_id);

COMMIT;