CREATE TABLE area_units (
    area_unit_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    abbreviation VARCHAR(10) NOT NULL UNIQUE
);

CREATE TABLE farm_states (
    farm_state_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(45) NOT NULL UNIQUE
);

CREATE TABLE farms (
    farm_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    area NUMERIC(10,2) NOT NULL,
    area_unit_id INTEGER NOT NULL,
    farm_state_id INTEGER NOT NULL,
    CHECK (area > 0)
);

CREATE TABLE user_role_farm_states (
    user_role_farm_state_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(45) NOT NULL UNIQUE
);

CREATE TABLE user_role_farm (
    user_role_farm_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_role_id INTEGER NOT NULL,
    farm_id INTEGER NOT NULL,
    user_role_farm_state_id INTEGER NOT NULL,
    UNIQUE(user_role_id, farm_id)
);

CREATE TABLE coffee_varieties (
    coffee_variety_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE plot_states (
    plot_state_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(45) NOT NULL UNIQUE
);

CREATE TABLE plots (
    plot_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    longitude NUMERIC(11, 8) CHECK (longitude BETWEEN -180 AND 180),
    latitude NUMERIC(11, 8) CHECK (latitude BETWEEN -90 AND 90),
    altitude NUMERIC(10, 2) CHECK (altitude >= 0 AND altitude <= 3000),
    coffee_variety_id INTEGER NOT NULL,
    farm_id INTEGER NOT NULL,
    plot_state_id INTEGER NOT NULL,
    UNIQUE(name, farm_id)
);

-- FOREIGN KEYS

ALTER TABLE farms
    ADD CONSTRAINT fk_farm_area_unit_id FOREIGN KEY (area_unit_id) REFERENCES area_units(area_unit_id);

ALTER TABLE farms
    ADD CONSTRAINT fk_farm_farm_state_id FOREIGN KEY (farm_state_id) REFERENCES farm_states(farm_state_id);

ALTER TABLE plots
    ADD CONSTRAINT fk_plot_coffee_variety_id FOREIGN KEY (coffee_variety_id) REFERENCES coffee_varieties(coffee_variety_id);

ALTER TABLE plots
    ADD CONSTRAINT fk_plot_farm_id FOREIGN KEY (farm_id) REFERENCES farms(farm_id) ON DELETE CASCADE;

ALTER TABLE plots
    ADD CONSTRAINT fk_plot_plot_state_id FOREIGN KEY (plot_state_id) REFERENCES plot_states(plot_state_id);

ALTER TABLE user_role_farm
    ADD CONSTRAINT fk_user_role_farm_farm_id FOREIGN KEY (farm_id) REFERENCES farms(farm_id) ON DELETE CASCADE;

ALTER TABLE user_role_farm
    ADD CONSTRAINT fk_user_role_farm_user_role_farm_state_id FOREIGN KEY (user_role_farm_state_id) REFERENCES user_role_farm_states(user_role_farm_state_id);