CREATE TABLE invitation_states (
    invitation_state_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(45) NOT NULL UNIQUE
);

CREATE TABLE invitations (
    invitation_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invited_user_id INTEGER NOT NULL,
    suggested_role_id INTEGER NOT NULL,
    invitation_state_id INTEGER NOT NULL,
    farm_id INTEGER NOT NULL,
    inviter_user_id INTEGER NOT NULL,
    invitation_date TIMESTAMP WITH TIME ZONE NOT NULL,
    UNIQUE(invited_user_id, farm_id)
);

-- FOREIGN KEYS

ALTER TABLE invitations
    ADD CONSTRAINT fk_invitation_invitation_state_id FOREIGN KEY (invitation_state_id) REFERENCES invitation_states(invitation_state_id);