CREATE TABLE invitation_states (
    invitation_state_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(45) NOT NULL UNIQUE
);

CREATE TABLE invitations (
    invitation_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    referral_user_id INTEGER NOT NULL,
    suggested_role_id INTEGER NOT NULL,
    invitation_state_id integer NOT NULL,
    farm_id integer NOT NULL,
    referrer_user_id integer NOT NULL,
    invitation_date timestamp with time zone NOT NULL,
    UNIQUE(referral_user_id, farm_id)
);

-- FOREIGN KEYS

ALTER TABLE invitations
    ADD CONSTRAINT fk_invitation_invitation_state_id FOREIGN KEY (invitation_state_id) REFERENCES invitation_states(invitation_state_id);