-- BASIC CONFIGURATION
SET client_encoding = 'UTF8';

BEGIN;

-- TABLES
CREATE TABLE coffee_variety (
    coffee_variety_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);

CREATE TABLE plot_status (
    status_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(45) NOT NULL
);

CREATE TABLE plot (
    plot_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    longitude NUMERIC(11, 8) CHECK (longitude BETWEEN -180 AND 180),
    latitude NUMERIC(11, 8) CHECK (latitude BETWEEN -90 AND 90),
    altitude NUMERIC(10, 2),
    coffee_variety_id integer NOT NULL,
    farm_id integer NOT NULL,
    status_id integer NOT NULL
);

-- FOREIGN KEYS

ALTER TABLE plot
    ADD CONSTRAINT fk_plot_coffee_variety_id FOREIGN KEY (coffee_variety_id) REFERENCES coffee_variety(coffee_variety_id);

ALTER TABLE plot
    ADD CONSTRAINT fk_plot_status_id FOREIGN KEY (status_id) REFERENCES plot_status(status_id);

COMMIT;