CREATE TABLE transaction_states (
    transaction_state_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(45) NOT NULL UNIQUE
);

CREATE TABLE transaction_types (
    transaction_type_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE transaction_categories (
    transaction_category_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    transaction_type_id INTEGER NOT NULL,
    UNIQUE(name, transaction_type_id)
);

CREATE TABLE transactions (
    transaction_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description VARCHAR(255),
    plot_id INTEGER NOT NULL,
    transaction_date DATE NOT NULL,
    transaction_state_id INTEGER NOT NULL,
    value NUMERIC(15, 2) NOT NULL,
    transaction_category_id INTEGER NOT NULL,
    creator_id INTEGER NOT NULL
);

-- FOREIGN KEYS

ALTER TABLE transactions
    ADD CONSTRAINT fk_transaction_transaction_category_id FOREIGN KEY (transaction_category_id) REFERENCES transaction_categories(transaction_category_id);

ALTER TABLE transactions
    ADD CONSTRAINT fk_transaction_transaction_state_id FOREIGN KEY (transaction_state_id) REFERENCES transaction_states(transaction_state_id);

ALTER TABLE transaction_categories
    ADD CONSTRAINT fk_transaction_type FOREIGN KEY (transaction_type_id) REFERENCES transaction_types(transaction_type_id) ON DELETE CASCADE;