CREATE TABLE transaction_states (
    transaction_state_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(45) NOT NULL UNIQUE
);

CREATE TABLE transaction_types (
    transaction_type_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE transaction_categories (
    transaction_category_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    transaction_type_id integer NOT NULL,
    UNIQUE(name, transaction_type_id)
);

CREATE TABLE transactions (
    transaction_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plot_id integer NOT NULL,
    description VARCHAR(255),
    transaction_date date NOT NULL,
    transaction_state_id integer NOT NULL,
    value numeric(15, 2) NOT NULL,
    transaction_category_id integer NOT NULL,
    creator_id integer NOT NULL
);

-- FOREIGN KEYS

ALTER TABLE transactions
    ADD CONSTRAINT fk_transaction_transaction_category_id FOREIGN KEY (transaction_category_id) REFERENCES transaction_categories(transaction_category_id);

ALTER TABLE transactions
    ADD CONSTRAINT fk_transaction_transaction_state_id FOREIGN KEY (transaction_state_id) REFERENCES transaction_states(transaction_state_id);

ALTER TABLE transaction_categories
    ADD CONSTRAINT fk_transaction_type FOREIGN KEY (transaction_type_id) REFERENCES transaction_types(transaction_type_id) ON DELETE CASCADE;